language: swift
osx_image: xcode10.1

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

sudo: false

xcode_project: SideMenu.xcodeproj
xcode_scheme: SideMenu
script: xcodebuild -project SideMenu.xcodeproj -scheme SideMenu -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' build